openapi: 3.0.0
info:
  title: "georeference and distance calculator"
  description: "Georeferences input addresses in json format"
  version: '1.0'

servers:
- url: /api/v1

paths:
  /georef:
    post:
      description: Georeferences a given set of addresses
      operationId: georefPost
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/inputFormatGeoreference'
                - $ref: '#/components/schemas/inputWithXls'
          
      responses:
        200:
          description: Addresses georeferenced correctly
          content:

            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/resolutionInline'
                  - $ref: '#/components/schemas/ID'
                  - $ref: '#/components/schemas/URL'
                  - $ref: '#/components/schemas/xlsPath'
        400:
          description: One or more invalid addresses
        404:
          description: One or more addresses do not exist
      
  /georef/{id}:
    parameters:
      - name: id
        in: path
        description: ID linked to a list of resolutions
        required: true
        schema:
          type: string

    get:
      description: Returns the list of address resoultions linked to a given ID
      operationId: georefIdGet
      responses:
      
        200:
          description: 'Success: ID exists'
          content:

            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/resolutionInline'
                  - $ref: '#/components/schemas/xlsPath'

        400:
          description: Invalid ID
          
        404:
          description: ID does not exist, no resolutions found

    delete:
      responses:
        204:
          description: Resolutions deleted
        400:
          description: Invalid ID
        404:
          description: ID does not exist, no resolutions will be deleted
  
  /dm:
    post:
      description: Returns the distance matrix of a given set of georeferenced addresses
      operationId: dmPost
      requestBody:
        required: true
        content:
        
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/inputFormatDistanceMatrix'
                - $ref: '#/components/schemas/inputWithXls'
          
      responses:
        200:
          description: Distances calculated correctly
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ID'
                  - $ref: '#/components/schemas/URL'
                  - $ref: '#/components/schemas/xlsPath'
        404:
          description: Could not calculate one or more distances

  /dm/{id}:
    parameters:
      - name: id
        in: path
        description: ID linked to a calculated distance matrix
        schema:
          type: string
        required: true

    get:
      description: Returns a distance matrix linked to a given ID
      operationId: dmIdGet
      responses:
        200:
          description: ID exists, getting the distance matrix
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/xlsPath'
        
        400: 
          description: Invalid ID
        
        404: 
          description: ID does not exist, no matrices found

    delete:
      description: Deletes matrix' id
      operationId: dmIdDelete
      responses:
        204:
          description: Matrix deleted
        400:
          description: Invalid ID
        404:
          description: ID does not exist, no matrices will be deleted
  
components:
  schemas:
  
    inputFormatGeoreference:
      type: object
      properties:
        resolutionType:
          $ref: '#/components/schemas/resolutionType'
        addressInformations:
          $ref: '#/components/schemas/addressesList'
          
    inputWithXls:
      type: object
      properties:
        resolutionType:
          $ref: '#/components/schemas/resolutionType'
        filePath:
          $ref: '#/components/schemas/xlsPath'
          
    inputFormatDistanceMatrix:
      type: object
      properties:
        resolutionType:
          $ref: '#/components/schemas/resolutionType'
        georeferencedAddress:
          $ref: '#/components/schemas/resolutionInline'
    
    resolutionType:
      type: string
      enum: [ID, Inline, URL]

    addressesList:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          address:
            type: string
          area:
            type: string
          district:
            type: string
          zipCode:
            maximum: 98100
            minimum: 10
            type: integer
          region:
            type: string
          country:
            type: string
          
    resolutionInline:
      type: array
      items:
        type: object
        properties:
          address:
            type: string
          latitude:
            type: number
            format: double
          longitude:
            type: number
            format: double
    
    distanceMatrix:
      type: array
      items:
        type: array
        items:
          type: object
          properties:
            kmDistance:
              type: number
              format: float
            time:
              type: string
    
    ID:
      type: string
      format: uuid
      
    URL:
      type: string
      format: url
      
    xlsPath:
      type: string
      format: path
      
